<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DKRGVPD7GE"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DKRGVPD7GE');
</script>

# Rationale
A significant challenge in controlling cholera transmission in Sub-Saharan Africa (SSA) is the lack of comprehensive datasets and dynamic models designed to support ongoing policy-making. The persistent endemic nature of cholera in SSA presents a complex quantitative challenge, requiring sophisticated models to produce meaningful inferences. Models that incorporate the necessary natural history and disease dynamics, and operate at adequate spatial and temporal scales, are crucial for providing timely and actionable information to address ongoing and future cholera outbreaks.

Although developing data and models at these scales is challenging, our goal is to iteratively create a landscape-scale transmission model for cholera in SSA that can provide weekly predictions of key epidemiological metrics. Our modeling methods will leverage a wide array of up-to-date data sources, including incidence and mortality reports, patterns of human movement, vaccination history and schedules, and environmental factors.

Key questions to address include when and where to administer a limited supply of oral cholera vaccine (OCV) and how severe weather events and climate change will impact future outbreaks. A landscape-scale model that accounts for endemic transmission patterns will be a valuable tool in addressing these questions.
