<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DKRGVPD7GE"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DKRGVPD7GE');
</script>


# Scenarios

A key aim of the MOSAIC model is to provide near-term forecasts of cholera transmission in Sub-Saharan Africa (SSA) using the most current data available. However, MOSAIC is not just a forecasting tool; it is a dynamic model designed to explore various scenarios that influence critical factors such as vaccination, environmental conditions, and Water, Sanitation, and Hygiene (WASH) interventions.

## Vaccination 

### Spatial and Temporal Strategies

Understanding the spatial and temporal distribution of cholera vaccination efforts is crucial for effective outbreak control. Key resources include:

- **Stockpile Status**: The availability of the oral cholera vaccine in emergency stockpiles can be tracked through UNICEF's [Emergency Stockpile Availability](https://www.unicef.org/supply/documents/emergency-stockpile-availability-oral-cholera-vaccine).
- **WHO OCV Dashboard**: This dashboard ([link](https://app.powerbi.com/view?r=eyJrIjoiYmFmZTBmM2EtYWM3Mi00NWYwLTg3YjgtN2Q0MjM5ZmE1ZjFkIiwidCI6ImY2MTBjMGI3LWJkMjQtNGIzOS04MTBiLTNkYzI4MGFmYjU5MCIsImMiOjh9)) provides insights into the deployment of oral cholera vaccines (OCV) across different regions.

### Reactive Vaccination

The timing and logistics of reactive vaccination campaigns are critical for controlling ongoing outbreaks. Relevant resources include:

- **WHO Recommended Timing**: Guidelines and recommendations for the timing of reactive OCV campaigns are available from the WHO ([link](https://www.who.int/groups/icg/cholera/stockpiles)).
- **Requests and Delay Time Distributions**: Information on vaccine request processes and the distribution of delays in vaccine deployment can be accessed through the GTFCC OCV Dashboard ([link](https://apps.epicentre-msf.org/public/app/gtfcc)).

## Impacts of Climate Change

### Severe Weather Events

Projections of climate shocks, including the frequency and severity of cyclones and floods, are essential for modeling the future impacts of climate change on cholera transmission. Key references include:

- **Chen and Chavas 2020**: A study on cyclone season dynamics under climate change scenarios ([link](https://journals.ametsoc.org/view/journals/atsc/77/8/jasD190320.xml)).
- **Sparks and Toumi 2024**: Research on projected flood frequencies due to climate change ([link](https://www.nature.com/articles/s41597-024-03250-y)).
- **Switzer et al. 2023**: An analysis of climate shock impacts on cholera outbreaks ([link](https://www.nature.com/articles/s43247-023-00844-z)).

### Long-Term Trends

Long-term trends in weather variables under various climate change scenarios can be explored using the following resource:

- **Weather Variables Under Climate Change**: The OpenMeteo Climate API provides access to projected weather data under different climate change scenarios ([link](https://open-meteo.com/en/docs/climate-api)).

